server.port=8082
spring.application.name=catalog

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogdb
spring.datasource.username=reto
spring.datasource.password=reto123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
