server.port=8081
security.jwt.secret=MiClaveSuperSecretaMuyLarga1234567890ABCDEF
security.jwt.expiration-minutes=15
server.error.include-message=always
server.error.include-stacktrace=always
security.jwt.secret=LA_MISMA_SECRET_QUE_USASTE_EN_AUTH_SERVICE