server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Crea las tablas automáticamente basado en tus clases Java
    show-sql: true