server.port=8083
spring.application.name=orders-service

# Actuator (reto: /actuator/health) - Sprint 1
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
